README.md
The ebuild is not yet part of the official repository, but can be installed by anyone willing to enable the kske overlay.
=> Document availability in Gentoo Linux in README

share/gtk-pipe-viewer.glade
Basically, I've changed the `hbox1` container position below the menu. Now the search bar is accessible from everywhere.
Closes #14
=> GUI: Change position of the search bar

lib/WWW/PipeViewer/InitialData.pm, lib/WWW/PipeViewer/Proto.pm
Correctly support different combinations of ordering and filters (e.g. like sorting by upload date and for only short HD videos), as well as paging.
Partially fix #57.
Example:
```bash
▸ ./pipe-viewer --order=upload_date --hd 'drum playthrough' 
1. NOCTURNAL BLOODLUST - Dagger (Drum Playthrough by Natsu)                  NOCTURNAL BLOODLUST  1d  1.7K    04:18
2. DISTANT - ''Aeons Of Oblivion'' Drum Playthrough                          DISTANT              1m  2.3K    04:02
3. Whitechapel - A Bloodsoaked Symphony (Drum Playthrough)                   Metal Blade Records 10m  198K    04:30
4. LORNA SHORE - Austin Archey - King Ov Deception (OFFICIAL DRUM PLAYTHROUG Century Media Recor  1y  282K    04:01
5. Polyphia - Playing God (Drum Playthrough)                                 Polyphia …
```
=> fix building of Youtube search parameters

bin/gtk-pipe-viewer, bin/pipe-viewer, lib/WWW/PipeViewer.pm, lib/WWW/PipeViewer/InitialData.pm, lib/WWW/PipeViewer/Search.pm, share/gtk-pipe-viewer.glade
Improve support for video features filtering: `hd`, `subtitles`, `creative_commons`, `3d`, `live`, `4k`, `360`, `hdr`, and `vr180`. Both the CLI parameters and the GUI have been updated accordingly.
Improve the GUI:
- use IDs rather than indexes when dealing with comboboxes: improve labels and make translations possible
- save back the state of most of those comboboxes (settings panel) to the configuration
Notes:
- the `location` and `purchased` features are not supported, I don't login to Youtube, so there's no way for me to test, but it should be pretty easy to add them.
- this increase the version number of some of the requirements: `List::Util>=1.45` (for `uniq`, released 2016-03-25), `Gtk>=3.12` (for `GtkFlowBox`, released 2014-03-25), `Scalar::Util>=1.39` (for `looks_like_number`, …
=> improve Youtube search and the GUI

bin/gtk-pipe-viewer, share/gtk-pipe-viewer.glade
Include moving the "Find" button next to the search field.
~I've only gone through the "Settings" pane for now, but I can do the same with the "Channel" pane.~
Before:
After:
=> gui: tweak interface to be less cramped

lib/WWW/PipeViewer/Search.pm
Apparently, instances don't honor `sort_by` (as per the [documentation](https://github.com/iv-org/documentation/blob/master/docs/api.md#get-apiv1search)) and `sort=date|relevance|rating|views` should be used instead.
=> fix building of Invidious search parameters

share/gtk-pipe-viewer.glade
The bug:
- focus the start page or / max results widget
- change the value
- press enter to "activate" the widget and initiate a search
→ the new value is not used.
=> gui: fix start page max results controls

bin/gtk-pipe-viewer, lib/WWW/PipeViewer.pm, lib/WWW/PipeViewer/InitialData.pm, lib/WWW/PipeViewer/Utils.pm, share/gtk-pipe-viewer.glade
The gist of it: slightly bigger thumbnails (no use wasting space), no upscaling, keep aspect-ratio when downscaling, better cache handling, and the `thumbnail_type       => 'medium',` settings is now `thumbnail_size              => '224x126'` (with correct support for bigger sizes).
=> overhaul thumbnails handling

bin/gtk-pipe-viewer, share/gtk-pipe-viewer.glade
Use a dialog, instead of another top-level window, so "escape to close" is automatically supported, and the close button can be simplified to use the corresponding response.
Use a generic hide/show callback to avoid the need for a bunch of specific ones.
If there are corresponding menu items, just set our shortcuts for showing each dialog there.
Incidentally, this fix a Gtk warning when closing the errors window:
```
FATAL: could not convert value 0 to enum type GtkResponseType at […]/Gtk3.pm line 285.
```
=> gui: simplify how a number of child windows are handled

share/gtk-pipe-viewer.glade
This look like a lot of changes but it just removes an empty box (previously holding the status bar), and as a consequence an unnecessary parent container.
=> gui: small cleanup

bin/gtk-pipe-viewer, bin/pipe-viewer, lib/WWW/PipeViewer/Channels.pm, lib/WWW/PipeViewer/PlaylistItems.pm, lib/WWW/PipeViewer/Playlists.pm, share/gtk-pipe-viewer.glade
- getting a channel's likes/favorites is unsupported, remove the corresponding code and simplify the GUI "Channel" panel.
- remove `WWW::PipeViewer::(playlists|uploads)_from_username` methods: they are just aliases for `videos_from_channel_id`, which already handle both cases (passing a channel ID or a channel's username with no spaces), and rename `videos_from_channel_id` to `uploads`.
- simplify the the CLI and GUI code accordingly (including, again, the GUI "Channel" panel).
- fix listing the videos of a comment author in the CLI
IMHO, we should just remove the GUI "Channel" panel, maybe remove the 2 entries in the users list window too, rational:
- listing a channel playlists / uploads by username is severely limited: it only works when there's no space in the username, and only for …
=> cleanup channel related features

lib/WWW/PipeViewer/VideoCategories.pm, lib/WWW/PipeViewer/Videos.pm
- Invidious' API actually expects the category type argument to be capitalized
- "News" is not a supported category
=> fix categories handling

bin/gtk-pipe-viewer, bin/pipe-viewer, lib/WWW/PipeViewer/Utils.pm, share/gtk-pipe-viewer.glade
Give more space to the description by making the details panel more compact and moving the link button to the bottom of the button box.
Before:
After:
When a number is shortened, the full value is available as a tooltip:
Note: the category name is not displayed, as for now it's never available with the method used to get a video details.
=> GUI: tweak details window

MANIFEST, bin/gtk-pipe-viewer, bin/pipe-viewer, lib/WWW/PipeViewer.pm, lib/WWW/PipeViewer/Channels.pm, lib/WWW/PipeViewer/CommentThreads.pm, lib/WWW/PipeViewer/DiskCache.pm, lib/WWW/PipeViewer/InitialData.pm, lib/WWW/PipeViewer/ParseJSON.pm, lib/WWW/PipeViewer/Search.pm, lib/WWW/PipeViewer/Utils.pm, lib/WWW/PipeViewer/Videos.pm, lib/WWW/PipeViewer/Worker.pm, share/gtk-pipe-viewer.glade
To avoid freezing the GUI.
Notes:
- the worker process is forked, but a new interpreter is then started to ensure a clean slate: I could not find a way to dynamically require `Gtk et al.` only in the main process.
- the worker process higher priority requests first (FIFO order).
- the worker still process only one request at a time, so if for example the Invidious instance is down, a timeout of the current request can take a while and delay other (including higher priority) requests.
- the thumbnails are now independently saved to disk in `~/.cache/pipe-viewer`.
- ~the results list is now cleared **before** sending a new search request (instead of before displaying the results), rational: there's no much point in being able to keep interacting with the current results as most search …
=> gui: move network calls to a dedicated process

bin/gtk-pipe-viewer
Ensure it's really at the top, and not half-way to the first result…
=> gui: fix results initial scroll position

bin/gtk-pipe-viewer, share/gtk-pipe-viewer.glade
Switch to a text view for displaying the comments. This has several advantages:
- the comments are automatically re-wrapped when the window is resized
- easier and better formatting (colors, indentation, …)
- allow text selection and copying
Additionally, fix support for replies.
Demo:
TODO:
=> gui: rework the comments window

bin/gtk-pipe-viewer
Due to the button start mark gravity, it would break after expansion of a preceding "replies" button.
=> gui: fix flaky "load more" comments button

bin/gtk-pipe-viewer
Ensure the result is selected **and** focused when right clicking to bring up the popup menu.
Close #126.
=> gui: fix results focus handling

bin/gtk-pipe-viewer, share/gtk-pipe-viewer.glade
- use placeholder text when applicable
- use a secondary "clear" icon for clearing and focusing
- get rid of the `clear_text_entries_on_click` setting
=> gui: improve handling of text entries

share/gtk-pipe-viewer.glade
Asking for lower does not work with Youtube, and the Invidious API always returns 20 results.
=> gui: set "number of results per page" minimum to 20

bin/gtk-pipe-viewer, bin/pipe-viewer
```
> cd /tmp
> git clone https://github.com/trizen/pipe-viewer
> ln -s pipe-viewer/bin/pipe-viewer     yt
> ln -s pipe-viewer/bin/gtk-pipe-viewer yg
> ./yt
Can't locate WWW/PipeViewer.pm in @INC (you may need to install the WWW::PipeViewer module) ...
> ./yg
Can't locate WWW/PipeViewer.pm in @INC (you may need to install the WWW::PipeViewer module) ...
```
With $FindBin::RealBin it can lauch OK.
But I didn't look deeper into the code - it might require additional edits - I just dunno, please revise it yourself.
And thanks for great software! 😎
=> fix launch via a symlink

lib/WWW/PipeViewer/Utils.pm
The time "6m" is not parsed, since it doesn't have a second component. Therefore, we also let the second component be optional so that times only containing an hour and/or minute component will parse. Example: https://www.youtube.com/watch?v=ZKgPxUPOBqc&t=6m
Additionally, ensure that the entire string matches the regexes, since https://www.youtube.com/watch?v=ZKgPxUPOBqc&t=42lol technically passes otherwise.
=> More strictly and properly parse start time

bin/gtk-pipe-viewer, bin/pipe-viewer, lib/WWW/PipeViewer.pm
closes #204
i remove some comments and refactor the man of my previous commit
i removed mpvraw
adding option to not extract video/audio urls, instead pass the page url to the player, so that it can do the extraction.
added to documentation
tested
The extraction, takes ~1 minute, if you need some feature of the player, for example sponsorblock, it does the extraction again, and that's ~2 minutes total. That's quite the annoyance.
normally, only player playback is affected. Download and other features stay unaffected. Playback configuration doesn't work(resolutions etc), because you outsource all that to the player.
=> option: youtube extraction to the player

lib/WWW/PipeViewer/Utils.pm
oupsy
if the locale thousands separator is '.', the regex interprets it as any character, and just crops the first character.
This makes the separator a literal character. So only it get's cropped.
=> fix set_thousands regex when separator is .
